[package]
name = "k3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
crossterm.workspace = true
k3-core = { path = "../k3-core" }
hound = "3.5.1"
lofty = "0.24.0"
ratatui.workspace = true
rodio = "0.22.2"
rodio-wsola = "0.2.0"
rtrb = "0.3.4"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ureq = { version = "3.4.0", features = ["json"] }
unicode-width = "0.2.1"
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
