[package]
name = "k3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
crossterm.workspace = true
k3-core = { path = "../k3-core" }
ratatui.workspace = true
rodio = "0.22.2"
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
